version: "3.1"
volumes:
  data:
services:
  db:
    image: "mariadb"
    restart: always
    volumes:
      - data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: newProjectAppDB
      MYSQL_USER: root
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: admin
